---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: ai-verify
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
patches:
- patch-deployment.yaml
- patch-ingress.yaml
